language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

before_script:

install:

#TODO:
#let scopeNameTest.py run on a small sample of most recently processed files after a commit (~ 100).

script:
  - pwd
  - python ./testing/deobfuscate_tests.py
  - python ./testing/evalRenamingTests.py
  - python ./testing/testVariableMetrics.py
  - python ./testing/testScopeDefinition.py

notifications:
  email: false
