language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

before_script:

install:

script:
  # Your test script goes here
  - python deobfuscator/testing/deobfuscate_tests.py
