language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

before_script:

install:

script:
  - pwd
  - python ./testing/deobfuscate_tests.py
  - python ./testing/evalRenamingTests.py

notifications:
  email: false
