cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3307779.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1263749.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3472010.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4052619.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3443471.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2504976.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4222737.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4039570.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1259924.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/247957.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4991128.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/43420.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2788125.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/278174.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/3597893.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1570849.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/508324.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2905169.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4008616.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2989212.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1275562.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4073133.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/201006.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1305265.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744179.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4306101.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1770040.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1990356.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1974077.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348853.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4416849.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1379936.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1961157.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/5279444.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4348873.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/253519.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1744184.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/259412.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4666965.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325721.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1710684.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2619485.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/224992.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2511953.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4325741.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4577134.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932015.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/4212471.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1932025.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/2733053.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.u.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.hash_def_one_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.hash_def_one_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.hash_def_one_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.hash_def_one_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.no_renaming.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.no_renaming.freqlen.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.no_renaming.lmdrop.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
cp /data/bogdanv/deobfuscator/experiments/results/sample.test.10k.v10/1847166.no_renaming.lm.js /home/ccasal/jsnaughty/testing/consistencyFailureFiles/
